## AMAN GOUND 
## ROLL : 103
## date : 22/1/2026
## topic : ML exp 1

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
print("arr from list:" , arr1)


arr from list: [1 2 3 4 5]


In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
arr_arange = np.arange(0,10,2)
print("aranged array :",arr_arange)


aranged array : [0 2 4 6 8]


In [5]:
# arr_linspace = np.linspace(start,stop,step(how many parts of division) )

arr_linspace = np.linspace(0,1,5)
print("linspace array:", arr_linspace)

linspace array: [0.   0.25 0.5  0.75 1.  ]


In [6]:
# arr_zeros = np.zeros((rows ,columns ))
arr_zeros = np.zeros((2,3))
print("zeros array:\n", arr_zeros)


zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# arr_ones = np.ones((rows ,columns ))
arr_ones = np.ones((3,2))
print("ones array:\n", arr_ones)

ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# creates an identity matrix - i.e. np.i - focus on pronounciation 
arr_eye = np.eye(3)
print("Identity matrix:\n", arr_eye)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:

print("Shape of arr2:", arr2.shape)
print("Size of arr2:", arr2.size)
print("Number of dimensions:", arr2.ndim)
print("Data type:", arr2.dtype)
print("Item size (bytes):", arr2.itemsize)

Shape of arr2: (2, 3)
Size of arr2: 6
Number of dimensions: 2
Data type: int64
Item size (bytes): 8


In [10]:

arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
print("Index 2:", arr[2])
print("Last element:", arr[-1])
print("Slice 1:4:", arr[1:4])

Original array: [10 20 30 40 50]
Index 2: 30
Last element: 50
Slice 1:4: [20 30 40]


In [11]:
'''

arr2d[0,:]: This is slicing the array to get the first row. The 0 specifies the first row, and : means "all columns." - SIMILARLY LATER

'''
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array:\n", arr2d)
print("First row:", arr2d[0,:])
print("Second column:", arr2d[:,1])
print("Submatrix:\n", arr2d[0:2,1:3])

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Second column: [2 5 8]
Submatrix:
 [[2 3]
 [5 6]]


In [12]:

a = np.array([1,2,3])
b = np.array([4,5,6])
print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a ** 2:", a**2)

a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
a ** 2: [1 4 9]


In [13]:

c = np.array([[1,2,3],[4,5,6]])
d = np.array([1,1,1])
print("Broadcasting sum:\n", c + d)

Broadcasting sum:
 [[2 3 4]
 [5 6 7]]


In [14]:

arr = np.array([1,4,9,16])
print("sqrt:", np.sqrt(arr))
print("exp:", np.exp(arr))
print("log:", np.log(arr))
print("sin:", np.sin(arr))
print("cos:", np.cos(arr))

sqrt: [1. 2. 3. 4.]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
log: [0.         1.38629436 2.19722458 2.77258872]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
cos: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [15]:

arr = np.array([[1,2,3],[4,5,6]])
print("Sum:", np.sum(arr))
print("Sum axis 0:", np.sum(arr, axis=0))
print("Sum axis 1:", np.sum(arr, axis=1))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Argmax:", np.argmax(arr))
print("Argmin:", np.argmin(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))

Sum: 21
Sum axis 0: [5 7 9]
Sum axis 1: [ 6 15]
Mean: 3.5
Max: 6
Min: 1
Argmax: 5
Argmin: 0
Standard deviation: 1.707825127659933
Variance: 2.9166666666666665


In [16]:

arr = np.arange(12)
print("Original array:", arr)
arr_reshaped = arr.reshape(3,4)
print("Reshaped 3x4 array:\n", arr_reshaped)
arr_flat = arr_reshaped.flatten()
print("Flattened array:", arr_flat)
arr_transpose = arr_reshaped.T
print("Transpose:\n", arr_transpose)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [17]:

a = np.array([1,2,3])
b = np.array([4,5,6])
print("Horizontal stack:", np.hstack((a,b)))
print("Vertical stack:\n", np.vstack((a,b)))

Horizontal stack: [1 2 3 4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]


In [18]:

arr = np.arange(9)
print("Original array:", arr)
print("Split into 3 parts:", np.split(arr, 3))

Original array: [0 1 2 3 4 5 6 7 8]
Split into 3 parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [19]:

arr = np.array([1,2,3,4])
arr_view = arr.view()
arr_copy = arr.copy()
arr_view[0] = 100
arr_copy[1] = 200
print("Original after view change:", arr)
print("Original after copy change:", arr)

Original after view change: [100   2   3   4]
Original after copy change: [100   2   3   4]


In [20]:

arr = np.array([10,20,30,40,50])
print("Elements > 25:", arr[arr>25])
indices = [0,2,4]
print("Fancy indexing:", arr[indices])

Elements > 25: [30 40 50]
Fancy indexing: [10 30 50]


In [21]:

rand_arr = np.random.rand(3,3) # uniform [0,1)
print("Random array:\n", rand_arr)

rand_int = np.random.randint(0,10,5)
print("Random integers:", rand_int)

normal_arr = np.random.randn(3,3) # standard normal
print("Normal distribution array:\n", normal_arr)

Random array:
 [[0.80079172 0.6606352  0.82651778]
 [0.54481679 0.96470444 0.43386791]
 [0.79363718 0.63924426 0.70603445]]
Random integers: [7 7 8 8 0]
Normal distribution array:
 [[ 0.8578721   1.27932602 -0.74693642]
 [ 0.17390295  0.98444484 -0.97578607]
 [ 0.65350045  0.61993832  0.84244732]]


In [22]:

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix multiplication:\n", np.dot(A,B))
print("Matrix determinant:", np.linalg.det(A))
print("Matrix inverse:\n", np.linalg.inv(A))
print("Eigenvalues and Eigenvectors:\n", np.linalg.eig(A))

Matrix multiplication:
 [[19 22]
 [43 50]]
Matrix determinant: -2.0000000000000004
Matrix inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues and Eigenvectors:
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [23]:

np.save('array.npy', arr)
loaded_arr = np.load('array.npy')
print("Loaded array:", loaded_arr)

Loaded array: [10 20 30 40 50]
